# Stage 1: Build the Go application
FROM golang:1.22 as builder
WORKDIR /app/user-services
COPY go.mod go.sum ./
RUN go mod download
COPY /user-services .
RUN go build -o main .

# Stage 2: Create a minimal runtime image
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/user-services ./main
EXPOSE 8080
CMD ["./main"]