version: '3.8'

services:
  user-service:
    build:
      context: ./user-services
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always    
    environment:
      DB_USER: "arpitsrivastava"
      DB_PASSWORD: "Rupam#rani1983"
      DB_NAME: "User-services"
      DB_HOST: "postgres" 
      DB_PORT: "5432"
    volumes:
      - user-data:/app/data
    networks:
      - app-network

  order-service:
    build:
      context: ./order-services
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
    volumes:
      - order-data:/app/data
    networks:
      - app-network

  payment-service:
    build:
      context: ./payment-services
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network

  notification-service:
    build:
      context: ./notification-services
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "arpitsrivastava"
      POSTGRES_PASSWORD: "Rupam#rani1983"
      POSTGRES_DB: "User-services"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arpitsrivastava"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  user-data:
  order-data:
  postgres-data:
  mongo-data:

networks:
  app-network:
    driver: bridge
