version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.users
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}

  order-service:
    build:
      context: .
      dockerfile: Dockerfile.orders
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME_ORDER}

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.payment  # Indentation was incorrect
    ports:
      - "8082:8082"

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile.notification
    ports:
      - "8084:8084"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
