# Stage 1: Build the Go application
FROM golang:1.22 as builder
WORKDIR /app/notification-services
COPY go.mod go.sum ./
RUN go mod download

# Copy the actual service files
COPY notification-services/. .  
RUN go build -o main .

# Stage 2: Create a minimal runtime image
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/notification-services ./main
EXPOSE 8084
CMD ["./main"]
